// JSON-LD blocks in real Shopify themes are almost always Liquid-templated
// (`{{ shop.name | json }}`, conditional members via `{% if %}`), so naive
// JSON.parse rejects the overwhelming majority of real-world JSON-LD as
// "malformed" — including Shopify's own official Dawn theme. This does a
// best-effort static repair: verify structure while treating dynamic values
// as opaque, without ever executing Liquid.

// `{{ product | structured_data }}` is Shopify's own filter for rendering a
// complete, already-valid JSON-LD document — there is nothing to statically
// parse, and it should never be reported as malformed.
const BARE_STRUCTURED_DATA_RE = /^\{\{-?\s*[\w.]+(?:\s*\|\s*\w+(?::[^|{}]*)?)*\s*-?\}\}$/;

function neutralizeConditionals(text: string): string {
  return text
    .replace(/\{%-?\s*(?:if|unless|elsif|else)\b[^%]*?-?%\}/g, "")
    .replace(/\{%-?\s*(?:endif|endunless)\s*-?%\}/g, "");
}

function neutralizeOutputs(text: string): string {
  let index = 0;
  return text.replace(/\{\{-?[\s\S]*?-?\}\}/g, (match, offset: number, full: string) => {
    index++;
    const precededByQuote = full[offset - 1] === '"';
    return precededByQuote ? `LIQUID_${index}` : `"LIQUID_${index}"`;
  });
}

export function tryParseLiquidJson(rawText: string): { json: unknown | null; parseError: string | null } {
  const trimmed = rawText.trim();
  if (!trimmed) return { json: null, parseError: "Empty block" };

  if (BARE_STRUCTURED_DATA_RE.test(trimmed)) {
    return { json: null, parseError: null }; // dynamically generated by Shopify, nothing to statically validate
  }

  try {
    return { json: JSON.parse(trimmed), parseError: null };
  } catch {
    // fall through to the Liquid-aware repair pass below
  }

  const repaired = neutralizeOutputs(neutralizeConditionals(rawText));
  try {
    return { json: JSON.parse(repaired), parseError: null };
  } catch (err) {
    return { json: null, parseError: err instanceof Error ? err.message : "Invalid JSON" };
  }
}
