// JSON-LD blocks in real Shopify themes are almost always Liquid-templated
// (`{{ shop.name | json }}`, conditional members via `{% if %}`), so naive
// JSON.parse rejects the overwhelming majority of real-world JSON-LD as
// "malformed" — including Shopify's own official Dawn theme. This does a
// best-effort static repair: verify structure while treating dynamic values
// as opaque, without ever executing Liquid.

// `{{ product | structured_data }}` is Shopify's own filter for rendering a
// complete, already-valid JSON-LD document — there is nothing to statically
// parse, and it should never be reported as malformed.
const BARE_STRUCTURED_DATA_RE = /^\{\{-?\s*[\w.]+(?:\s*\|\s*\w+(?::[^|{}]*)?)*\s*-?\}\}$/;

// A `{% for %}` loop building an array (e.g. per-variant offers) very
// commonly pairs with `{% unless forloop.last %},{% endunless %}` to place
// commas correctly only between rendered items. Our repair only ever
// simulates a single pass through the loop body, so that per-iteration
// comma logic collapses into a real trailing comma our approximation can't
// distinguish from a genuine authoring mistake — found auditing a
// real-world theme (Splash) that builds its Product JSON-LD offers array
// this way. Rather than statically executing Liquid to get an accurate
// iteration count, decline to validate JSON containing a loop at all.
const LOOP_TAG_RE = /\{%-?\s*for\b/;

function neutralizeConditionals(text: string): string {
  return text
    .replace(/\{%-?\s*(?:if|unless|elsif|else)\b[^%]*?-?%\}/g, "")
    .replace(/\{%-?\s*(?:endif|endunless)\s*-?%\}/g, "");
}

function neutralizeOutputs(text: string): string {
  let index = 0;
  return text.replace(/\{\{-?[\s\S]*?-?\}\}/g, (match, offset: number, full: string) => {
    index++;
    const precededByQuote = full[offset - 1] === '"';
    return precededByQuote ? `LIQUID_${index}` : `"LIQUID_${index}"`;
  });
}

// `@type` is essentially always a literal schema.org string (or array of
// them), never Liquid-templated — so it can be read directly off the raw
// text even when the surrounding block can't be fully parsed (e.g. a
// {% for %}-built array, see LOOP_TAG_RE above). Without this, a block like
// Splash's Product JSON-LD — whose "@type": "Product" sits above an
// unparseable loop-built "offers" array — would silently report as having
// no Product schema at all, a false "missing" finding worse than declining
// to validate the block's overall JSON syntax.
export function extractLiteralJsonLdTypes(rawText: string): string[] {
  const types = new Set<string>();
  for (const m of rawText.matchAll(/"@type"\s*:\s*"([A-Za-z]+)"/g)) types.add(m[1]);
  for (const m of rawText.matchAll(/"@type"\s*:\s*\[([^\]]*)\]/g)) {
    for (const s of m[1].matchAll(/"([A-Za-z]+)"/g)) types.add(s[1]);
  }
  return [...types];
}

export function tryParseLiquidJson(rawText: string): { json: unknown | null; parseError: string | null } {
  const trimmed = rawText.trim();
  if (!trimmed) return { json: null, parseError: "Empty block" };

  if (BARE_STRUCTURED_DATA_RE.test(trimmed)) {
    return { json: null, parseError: null }; // dynamically generated by Shopify, nothing to statically validate
  }

  if (LOOP_TAG_RE.test(trimmed)) {
    return { json: null, parseError: null }; // loop-driven content — cannot reliably simulate without executing Liquid
  }

  try {
    return { json: JSON.parse(trimmed), parseError: null };
  } catch {
    // fall through to the Liquid-aware repair pass below
  }

  const repaired = neutralizeOutputs(neutralizeConditionals(rawText));
  try {
    return { json: JSON.parse(repaired), parseError: null };
  } catch (err) {
    return { json: null, parseError: err instanceof Error ? err.message : "Invalid JSON" };
  }
}
