import { describe, expect, it } from "vitest";
import { parseJsonFile } from "./parseJsonFile";

describe("parseJsonFile", () => {
  it("parses a plain template with no leading comment", () => {
    const info = parseJsonFile(
      "templates/index.json",
      '{"sections": {"a": {"type": "hero"}}, "order": ["a"]}'
    );
    expect(info.parseError).toBeNull();
    expect(info.sectionReferences).toEqual([{ line: 1, kind: "section", name: "hero", dynamic: false }]);
  });

  // Regression test: Shopify's own tooling (admin theme editor, `shopify
  // theme pull`) writes an auto-generated block comment at the top of JSON
  // files it manages. Found auditing Shopify's own Skeleton theme, where
  // this silently broke extraction for 14 of 17 JSON files since strict
  // JSON.parse rejects the whole file over an illegal leading comment.
  it("strips a Shopify-style leading block comment before parsing", () => {
    const raw = [
      "/*",
      " * IMPORTANT: auto-generated by the Shopify admin theme editor.",
      " */",
      '{"sections": {"a": {"type": "hero"}}, "order": ["a"]}',
    ].join("\n");
    const info = parseJsonFile("templates/index.json", raw);
    expect(info.parseError).toBeNull();
    expect(info.sectionReferences).toEqual([{ line: 4, kind: "section", name: "hero", dynamic: false }]);
  });

  it("strips a leading line comment before parsing", () => {
    const raw = '// auto-generated\n{"sections": {"a": {"type": "hero"}}, "order": ["a"]}';
    const info = parseJsonFile("templates/index.json", raw);
    expect(info.parseError).toBeNull();
  });

  it("strips multiple leading comments in sequence", () => {
    const raw = '/* one */\n// two\n/* three */\n{"sections": {}}';
    const info = parseJsonFile("templates/index.json", raw);
    expect(info.parseError).toBeNull();
  });

  it("still reports a parse error for genuinely invalid JSON", () => {
    const info = parseJsonFile("templates/index.json", "{ not valid json");
    expect(info.parseError).not.toBeNull();
    expect(info.sectionReferences).toEqual([]);
  });

  it("does not strip a comment-like substring that isn't at the start of the file", () => {
    // A string value containing "//" must not be treated as a line comment.
    const info = parseJsonFile("config/settings_schema.json", '[{"settings":[{"id":"url","default":"https://example.com"}]}]');
    expect(info.parseError).toBeNull();
    expect(info.settingKeys).toEqual(["url"]);
  });

  it("extracts setting keys from config/settings_schema.json", () => {
    const info = parseJsonFile(
      "config/settings_schema.json",
      '[{"name": "Colors", "settings": [{"type": "color", "id": "bg"}, {"type": "header"}]}]'
    );
    expect(info.settingKeys).toEqual(["bg"]);
  });

  it("flattens locale keys and preserves pluralization groups as a single path", () => {
    const info = parseJsonFile(
      "locales/en.default.json",
      '{"cart": {"item_count": {"one": "1 item", "other": "{{ count }} items"}}}'
    );
    expect(info.localeKeys.sort()).toEqual(["cart.item_count.one", "cart.item_count.other"]);
  });

  it("extracts section references from a section GROUP file (sections/*.json), not just templates/", () => {
    const info = parseJsonFile(
      "sections/header-group.json",
      '{"type": "header", "sections": {"main": {"type": "main-header"}}, "order": ["main"]}'
    );
    expect(info.sectionReferences).toEqual([{ line: 1, kind: "section", name: "main-header", dynamic: false }]);
  });
});
